### ISSUE TITLE
ImportError: Module import failed for Digital Asset (digistore.digistore.doctype.digital_asset.digital_asset Error: cannot import name 'Self' from 'typing_extensions'

### ISSUE THREAD

**Issue by saru2020** [NagariaHussain/digistore#2]
I'm seeing this issue when i try to install your app in a new site for the first time:

`  File "/Users/saravanan_vij/Documents/Learnings/Other_Learnings/Tryouts/Frappe_26Sep2021/frappe-bench/apps/frappe/frappe/modules/utils.py", line 204, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for Digital Asset (digistore.digistore.doctype.digital_asset.digital_asset Error: cannot import name 'Self' from 'typing_extensions' (/Users/saravanan_vij/Documents/Learnings/Other_Learnings/Tryouts/Frappe_26Sep2021/frappe-bench/env/lib/python3.8/site-packages/typing_extensions.py))
`

and from the next try onwards, I'm seeing this issue:
`document.py", line 376, in db_insert
    raise frappe.DuplicateEntryError(self.doctype, self.name, e)
frappe.exceptions.DuplicateEntryError: ('Module Def', 'Digistore', IntegrityError(1062, "Duplicate entry 'Digistore' for key 'PRIMARY'"))`

**Comment by NagariaHussain** [comment]
Hey! I am looking into it and will try to fix it asap.

Thanks for reporting the issue @saru2020

**Comment by NagariaHussain** [comment]
I have pushed a fix. Please try removing and installing the `digistore` app again and let me know if it has been fixed for you :)

**Comment by saru2020** [comment]
hey, thanks for the quick turnaround.

I'm still getting this issue with the existing site:
frappe.exceptions.DuplicateEntryError: ('Module Def', 'Digistore', IntegrityError(1062, "Duplicate entry 'Digistore' for key 'PRIMARY'"))


But, I created a new site and it did get installed w/o any issues.

But, again, I'm not seeing the store getting loaded. 
I tried accessing the store via 'http://localhost:8001/store' but nothing is being listed even after I've added some items in the Digital Products doctype.

Is there any other config that I should be doing before accessing the webpage?

**Comment by saru2020** [comment]
Also, i came from your other library: `doppio`, which is interesting, where I'm facing an issue using that library as well. 

I've created a separate issue for the same there: https://github.com/NagariaHussain/doppio/issues/3

**Comment by NagariaHussain** [comment]
Hey, instead of http://localhost:8001/store use http://<your-site-name>:8001/store 

The site name is required, since there can be multiple sites on a bench (all on localhost), bench forwards traffic based on the site name.

**Comment by saru2020** [comment]
hi @NagariaHussain, thanks for your reply.

http://:8001/store --> this is not working, chrome takes me to a google search page only.

Also, I tried setting up a totally new frappe folder set up with just one single site and installing just the digistore app on it but I'm still getting the same issue.

http://localhost:8000/products --> shows 404 error page
http://localhost:8000/store --> shows an empty page
http://localhost:8000/purchases --> shows 404 error page


I really don't know what I'm missing, any other inputs?

**Comment by saru2020** [comment]
[this](https://github.com/NagariaHussain/doppio/issues/3#issuecomment-997437716) was the solution, finally which worked.
